blank_issues_enabled: true

contact_links:
  - name: Microsoft Security Response Center ğŸ”
    url: https://msrc.microsoft.com/create-report
    about: Please report security vulnerabilities here.
  - name: Windows Terminal Documentation issue ğŸ“„
    url: https://github.com/MicrosoftDocs/terminal/issues/new
    about: Report issues with the documentation for the Windows Terminal (in docs.microsoft.com/windows/terminal)
  - name: Console Documentation issue ğŸ“„
    url: https://github.com/MicrosoftDocs/console-docs/issues/new
    about: Report issues with the documentation for the Console (in docs.microsoft.com/windows/console)
