# Do not allow blank issues
blank_issues_enabled: false

contact_links:
  - name: ğŸ” Microsoft Security Response Center
    url: https://msrc.microsoft.com/create-report
    about: Please report security vulnerabilities here.
  - name: ğŸ“„ Windows Terminal Documentation issue
    url: https://github.com/MicrosoftDocs/terminal/issues/new
    about: Report issues with the documentation for the Windows Terminal (in https://docs.microsoft.com/windows/terminal/)
  - name: ğŸ“„ Console Documentation issue
    url: https://github.com/MicrosoftDocs/console-docs/issues/new
    about: Report issues with the documentation for the Console(in https://docs.microsoft.com/windows/console/)
